[Filter/NNFW] enable set-dim function
nnstreamer/nnstreamer pull request #2743
Opened 2020-09-16 09:14 UTC by jaeyun-jung

ONE supports API to set input info, remove unnecessary feature about changing input shape.

TODO:
1. We should wait next ONE release - maybe ONE 1.10 on next month.
2. After the next ONE release, consider to publish nnstreamer 1.6.x release.

Signed-off-by: Jaeyun <jy1210.jung@samsung.com>

2020-09-16 09:25 UTC, jaeyun-jung commented
@chunseoklee This PR will enable set-dimension function in nnstreamer.

2020-09-16 09:52 UTC, dongju-chae approved these changes

2020-09-17 02:54 UTC, gichan-jang approved these changes
LGTM

2020-09-17 03:04 UTC, kparichay requested changes
Please also enable the unit test for the same which is currently DISABLED `nnstreamer_nnfw_runtime_raw_functions.DISABLED_set_dimension`.

2020-09-17 03:25 UTC, jaeyun-jung commented
@kparichay ONE team will release 1.10 (next) on next month. Currently set-info API throws exception and it does not change output shape.

2020-09-17 04:08 UTC, kparichay approved these changes
LGTM

2020-09-18 08:12 UTC, myungjoo approved these changes
+1

2020-09-18 08:12 UTC, merged