[TensorIF] Fix unit test fail on arm arch
nnstreamer/nnstreamer pull request #2839
Opened 2020-10-28 02:24 UTC by gichan-jang

The pipeline state changed to NULL before saving the result file due to slow speed of arm.
Give enough time or wait until the file is created.

Signed-off-by: gichan-jang <gichan2.jang@samsung.com>

Self evaluation:
1. Build test: [ *]Passed [ ]Failed [ ]Skipped
2. Run test: [ *]Passed [ ]Failed [ ]Skipped

2020-10-28 03:00 UTC, myungjoo requested changes
g_usleep (1 SECOND) is too much.
Do polling-with-usleep.
Refer to https://github.com/nnstreamer/nnstreamer/blob/main/tests/unittest_util.c#L79

2020-10-28 10:05 UTC, gichan-jang commented
> g_usleep (1 SECOND) is too much.
> Do polling-with-usleep.
> Refer to https://github.com/nnstreamer/nnstreamer/blob/main/tests/unittest_util.c#L79

Thanks. I changed to check if the file was created as intended.

2020-10-29 06:28 UTC, myungjoo approved these changes
LGTM

2020-10-30 01:38 UTC, dongju-chae commented on tests/nnstreamer_if/unittest_if.cc
> +  _wait_pipeline_save_files (tmp1, content2, len2, size, 1000); \
tmp1 --> tmp2?

2020-10-30 01:47 UTC, gichan-jang commented on tests/nnstreamer_if/unittest_if.cc
> +  _wait_pipeline_save_files (tmp1, content2, len2, size, 1000); \
oh... Thank you! Fixed.

2020-10-30 01:48 UTC, dongju-chae approved these changes
LGTM

2020-10-30 02:44 UTC, merged