[Coverity] Resolve coverity issue
nnstreamer/nnstreamer pull request #3021
Opened 2021-01-22 06:50 UTC by gichan-jang

Resolve the coverity issue
 1. Unchecked return value
 2. Logically dead code

Signed-off-by: Gichan Jang <gichan2.jang@samsung.com>

Self evaluation:
1. Build test: [ *]Passed [ ]Failed [ ]Skipped
2. Run test: [ *]Passed [ ]Failed [ ]Skipped

2021-01-22 07:46 UTC, jaeyun-jung approved these changes

2021-01-23 09:11 UTC, myungjoo requested changes
Although this is unit-test, which does not affect the library we release, do NOT write functional codes inside ASSERT. 

```
ASSERT(some_routine)
```
-->
```
result = some_routine;
ASSERT(results);
```

2021-01-25 04:51 UTC, gichan-jang commented
> Although this is unit-test, which does not affect the library we release, do NOT write functional codes inside ASSERT.
> 
> ```
> ASSERT(some_routine)
> ```
> 
> -->
> 
> ```
> result = some_routine;
> ASSERT(results);
> ```

Thanks. Updated!

2021-01-25 06:35 UTC, myungjoo approved these changes

2021-01-25 06:35 UTC, merged