[Filter/Sub] Add alias option for backward compatibility.
nnstreamer/nnstreamer pull request #3437
Opened 2021-08-06 02:56 UTC by again4you

This patch newly adds the `alias` option for searching the sub-plugin. If the alias name is provided from ini file, then it could be used as sub-plugin.
* Searching sequence: exact match -> priority option -> alias option

Since the sub-plugin name of SRNPU is changed to `trix-engine`, this PR sets the alias option as trix-engine for the previous SRNPU sub-plugin.

**Self evaluation:**
1. Build test: [X]Passed [ ]Failed [ ]Skipped
2. Run test: [X]Passed [ ]Failed [ ]Skipped

2021-08-06 03:14 UTC, myungjoo requested changes
This is not general or extensible approach.
We need something that can be applied to any subplugins without the need for recompiling.

2021-08-06 03:21 UTC, jaeyun-jung commented on meson_options.txt
> +option('srnpu-alias', type: 'string', value: 'trix-engine', description: 'The alias name list of SRNPU sub-plugin. This option provides backward compatibility.')
Q: changing 'srnpu-alias' to 'trix-engine-alias'?

fw name is trix-engine and srnpu is option.
then, 'trix-engine-alias' value: 'srnpu' in meson_option and the group name in ini is [trix-engine]

2021-08-06 05:14 UTC, myungjoo commented
Interface Suggestion of ```nnstreamer.ini```: e.g.,
```
[filter-aliases]
tf = tensorflow
tf2 = tensorflow
c2 = caffe2
카페2 = caffe2
까페2 = caffe2
```

2021-08-17 07:27 UTC, gichan-jang approved these changes
LGTM

2021-08-17 09:36 UTC, jaeyun-jung approved these changes

2021-08-17 09:37 UTC, merged